spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  jpa:
    show-sql: true
  cloud:
    kubernetes:
      config:
        name: api-produto
      reload:
        enabled: true
management:
  metrics:
    enable:
      root: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics